### ISSUE TITLE
Only getting invalid response on Master side

### ISSUE THREAD

**Issue by ameerhazo** [ihormelnyk/opentherm_library#48]
Hello @ihormelnyk and everyone, thank you for providing this library to use for free. I'm trying to use the Slave example as a way to simulate a boiler. The Slave is receiving the requests from the Master without any problems. Unfortunately, the responses I have sent out from the Slave back to the Master has always been considered as invalid responses by the Master. Debugging the response frame showed me that I'm only receiving 0s from the Slave.  I would appreciate it if anyone who has had this problem to be able to give me tips on what they did to fix the problem. Thank you and kind regards.

Ameer

**Comment by ihormelnyk** [comment]
Hi @ameerhazo,
try to add a delay before sending the response
delay(20); //20..400ms, usually 100ms
ot.sendResponse(response);

**Comment by ameerhazo** [comment]
Hello @ihormelnyk, it worked! Thank you so much for being such a lifesaver :D

**Comment by MvRens** [comment]
I had the same issue and the delay (which was already in the Slave example) did not help. I eventually figured out the status was still on "DELAY" when sendResponse is called causing it to fail.

From what I could tell the only way the status is reset is if process() is called regularly, which of course it wasn't between the delay and the call to sendResponse. Not sure if this is due to more recent changes, but I'll leave my fix here without reopening the issue in case someone stumbles upon it like I did. I replaced the delay in processRequest with the code that is also found in sendRequest and that fixed it for me:

```cpp
    while (!ot.isReady())
    {
        ot.process();
        yield();
    }
```
